### ISSUE TITLE
unable to create tensor

### ISSUE THREAD

**Issue by toufunao** [cckuailong/SuperAdapters#2]
I used this repo to finetune QWen base model. But it reports error : ValueError : Unable to create tensor , you should probably activate truncation and/or padding with 'padding=True' 'trunction=True' to have batched tensors with the same length.Perhaps you features("Instruction" in this case) have excessive nesting(inputs type 'list' where type 'int' is expected).

32G V100
transformers 4.30.2
finetuned data format
{
"Instruction":"XXX"
"Input":"XXX"
"Output":"XXX"
}
Data is loaded as a json file with each line representing a complete data record.

**Comment by cckuailong** [comment]
Here is an example and maybe you should keep your keys(Instruction, Input, Output) lower case. https://github.com/cckuailong/SuperAdapters/blob/master/data/train/example.json

**Comment by toufunao** [comment]
Thanks for your contribution. I've solved the issue.
