### ISSUE TITLE
tokenizers & transformers  version conflict

### ISSUE THREAD

**Issue by qq632230376** [cckuailong/SuperAdapters#9]
1.When I install the environment with the pip install -r requirements.txt command，report an error

2.error info:
NFO: pip is looking at multiple versions of transformers to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 101) and tokenizers==0.15.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested tokenizers==0.15.0
    transformers 4.40.2 depends on tokenizers<0.20 and >=0.19

3.my python version is 3.10.0 

thanks!

**Comment by cckuailong** [comment]
https://github.com/cckuailong/SuperAdapters/commit/01a49b98126c02220a0d4c884663d25dd2b6c437
